export const MUNICIPIOS_TOLIMA = [
    'ALPUJARRA',
    'ALVARADO',
    'AMBALEMA',
    'ANZOATEGUI',
    'ARMERO GUAYABAL',
    'ATACO',
    'CAJAMARCA',
    'CARMEN DE APICALA',
    'CASABIANCA',
    'CHAPARRAL',
    'COELLO',
    'COYAIMA',
    'CUNDAY',
    'DOLORES',
    'ESPINAL',
    'FALAN',
    'FLANDES',
    'FRESNO',
    'GUAMO',
    'HERVEO',
    'HONDA',
    'IBAGUE',
    'ICONONZO',
    'LERIDA',
    'LIBANO',
    'MARIQUITA',
    'MELGAR',
    'MURILLO',
    'NATAGAIMA',
    'ORTEGA',
    'PALOCABILDO',
    'PIEDRAS',
    'PLANADAS',
    'PRADO',
    'PURIFICACION',
    'RIOBLANCO',
    'RONCESVALLES',
    'ROVIRA',
    'SALDAÑA',
    'SAN ANTONIO',
    'SAN LUIS',
    'SANTA ISABEL',
    'SUAREZ',
    'VALLE DE SAN JUAN',
    'VENADILLO',
    'VILLAHERMOSA',
    'VILLARRICA'
];
